Data:
  # Data parameters
  data_folder: "./"  # folder with JSON data files
  crop_size: 96  # crop size of target HR images
  scaling_factor: 4  # the scaling factor for the generator; the input LR images will be downsampled from the target HR images by this factor

Model:
  SRGAN: False # "True", "False" (choose True for SRGAN, False for SRResNet)

SRResNet:
  # Model parameters
  large_kernel_size: 9  # kernel size of the first and last convolutions which transform the inputs and outputs
  small_kernel_size: 3  # kernel size of all convolutions in-between, i.e. those in the residual and subpixel convolutional blocks
  n_channels: 64  # number of channels in-between, i.e. the input and output channels for the residual and subpixel convolutional blocks
  n_blocks: 16  # number of residual blocks

  # Learning parameters
  checkpoint: None  # path to model checkpoint, None if none
  batch_size: 16  # batch size
  start_epoch: 0  # start at this epoch
  iterations: 1000000  # number of training iterations
  workers: 4  # number of workers for loading data in the DataLoader
  lr: 0.0001  # learning rate
  grad_clip: None  # clip if gradients are exploding

SRGAN:
  # Generator parameters
  large_kernel_size_g: 9  # kernel size of the first and last convolutions which transform the inputs and outputs
  small_kernel_size_g: 3  # kernel size of all convolutions in-between, i.e. those in the residual and subpixel convolutional blocks
  n_channels_g: 64  # number of channels in-between, i.e. the input and output channels for the residual and subpixel convolutional blocks
  n_blocks_g: 16  # number of residual blocks
  srresnet_checkpoint: "./checkpoint_srresnet.pth.tar"  # filepath of the trained SRResNet checkpoint used for initialization

  # Discriminator parameters
  kernel_size_d: 3  # kernel size in all convolutional blocks
  n_channels_d: 64  # number of output channels in the first convolutional block, after which it is doubled in every 2nd block thereafter
  n_blocks_d: 8  # number of convolutional blocks
  fc_size_d: 1024  # size of the first fully connected layer

  # Learning parameters
  checkpoint: None  # path to model (SRGAN) checkpoint, None if none
  batch_size: 16  # batch size
  start_epoch: 0  # start at this epoch
  iterations: 2000000  # number of training iterations
  workers: 4  # number of workers for loading data in the DataLoader
  vgg19_i: 5  # the index i in the definition for VGG loss; see paper or models.py
  vgg19_j: 4  # the index j in the definition for VGG loss; see paper or models.py
  beta: 0.001  # the coefficient to weight the adversarial loss in the perceptual loss
  print_freq: 500  # print training status once every __ batches
  lr: 0.0001  # learning rate
  grad_clip: None  # clip if gradients are exploding